-- Waypoints and help text for World Soul Searching achievements
-- Structure: Keyed by achievement ID, with optional criteria-level data
-- Note: Waypoints are structured with 'kind' (point/area) and 'coordinates' array
-- Note: This file was generated by parsing WorldSoulSearching.lua and converting existing waypoint data

WorldSoulSearchingWaypoints = {
    -- Main achievement: Worldsoul-Searching (61451)
    [61451] = {
        _helpText = "Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning",
        helpText = " Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning",
    },
    
    -- Achievement 40435: Adventurer of the Isle of Dorn
    [40435] = {
        _helpText = "test 123",
        helpText = " Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning",
        criteria = {
            [68210] = {
                _helpText = "General area (Check WoWHead for more info)",
                helpText = " Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning Released on December 2, 2025. Patch 11.2.7, Midnight Prologue: The Warning",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 36, y = 75, title = "Rustul Titancap <King Mushroom>" }
                        }
                    }
                }
            },
            [68211] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 63, y = 68, title = "Sandres the Relicbearer" }
                        }
                    }
                }
            },
            [68212] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 59, y = 61, title = "Springbubble" }
                        }
                    }
                }
            },
            [68213] = {
                helpText = "General area (Check WoWHead for more info)",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 59, y = 61, title = "Warphorn" }
                        }
                    }
                }
            },
            [68214] = {
                helpText = "General area (Check WoWHead for more info)",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 42, y = 77, title = "Bloodmaw" }
                        }
                    }
                }
            },
            [68215] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 48, y = 61, title = "Emperor Pitfang" }
                        }
                    }
                }
            },
            [68216] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 51, y = 70, title = "Plaguehart" }
                        }
                    }
                }
            },
            [68217] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 54, y = 80, title = "Gar'loc <High Sea Shaman>" }
                        }
                    }
                }
            },
            [68218] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 26, y = 45, title = "Escaped Cutthroat" }
                        }
                    }
                }
            },
            [68219] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 58, y = 17, title = "Tempest Lord Incarnus" }
                        }
                    }
                }
            },
            [68220] = {
                helpText = "On top of mountain, can knock you off with slam",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 48, y = 27, title = "Kronolith, Might of the Mountain" }
                        }
                    }
                }
            },
            [68221] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 75, y = 28, title = "Shallowshell the Clacker" }
                        }
                    }
                }
            },
            [68222] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 57, y = 23, title = "Twice-Stinger the Wretched" }
                        }
                    }
                }
            },
            [68223] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 64, y = 41, title = "Flamekeeper Graz" }
                        }
                    }
                }
            },
            [68224] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 56, y = 28, title = "Clawbreaker K'zithix" }
                        }
                    }
                }
            },
            [68225] = {
                helpText = "Collect 10 Crackling Shards by killing any mobs in the Isle of Dorn and combine them to create a Storm Vessel. Use Storm Vessel to dispel Alunira's shield.",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 23, y = 58, title = "Alunira" }
                        }
                    }
                }
            },
            [68226] = {
                helpText = "On rotation with: Zovex, Kereke, Rotfist",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 31, y = 52, title = "Zovex <Violet Hold Prisoner>" }
                        }
                    }
                }
            },
            [68227] = {
                helpText = "On rotation with: Zovex, Kereke, Rotfist",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 31, y = 52, title = "Kereke <Violet Hold Prisoner>" }
                        }
                    }
                }
            },
            [68228] = {
                helpText = "On rotation with: Zovex, Kereke, Rotfist",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 31, y = 52, title = "Rotfist <Violet Hold Prisoner>" }
                        }
                    }
                }
            },
            [68229] = {
                helpText = "General area, check WoWHead for more info",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 74, y = 39, title = "Tephratennae" }
                        }
                    }
                }
            },
            [68230] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 70, y = 39, title = "Sweetspark the Oozeful" }
                        }
                    }
                }
            },
            [68231] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 73, y = 41, title = "Matriarch Charfuria" }
                        }
                    }
                }
            },
        }
    },
    
    -- Achievement 40434: Treasures of the Isle of Dorn
    [40434] = {
        helpText = "",
        criteria = {
            [68197] = {
                helpText = "Get Crab-Guiding Branch from Freysworn Letitia. When you have the branch, find 6 Pearlescent Shellcrabs",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 49, y = 30, title = "Tree's Treasure" },
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 38.5, y = 42, title = "Pearlescent Shellcrab 1" },
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 20, y = 58.5, title = "Pearlescent Shellcrab 2" },
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 50.5, y = 70.5, title = "Pearlescent Shellcrab 3" },
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 75, y = 49.5, title = "Pearlescent Shellcrab 4" },
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 70.5, y = 20, title = "Pearlescent Shellcrab 5" },
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 42, y = 27, title = "Pearlescent Shellcrab 6" }
                        }
                    }
                }
            },
            [68198] = {
                helpText = "Fish or buy on the auction house following items: 5x Dornish Pike, 1x Fish and Chips, 1x Goldengill Trout. Turn in to the Dalaran Sewer Turtle.",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 41, y = 74, title = "Turtle's Thanks" }
                        }
                    }
                }
            },
            [68199] = {
                helpText = "Use Lionel and find 5 Plump Snapcrab on the shore nearby",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 41, y = 60, title = "Magical Treasure Chest" }
                        }
                    }
                }
            },
            [68201] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 54, y = 19, title = "Mysterious Orb - Turn in location" },
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 53, y = 18.5, title = "Mysterious Orb - Find Peral first" }
                        }
                    }
                }
            },
            [68202] = {
                helpText = "Find Boskroot Cap mushroom to the south It has a random spawn point. Turn it it to the U'llort the Self-Exiled",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 55, y = 66, title = "Mushroom Cap" }
                        }
                    }
                }
            },
            [68203] = {
                helpText = "Talk with One-Eyed Thak and follow him",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 38, y = 44, title = "Thak's Treasure" }
                        }
                    }
                }
            },
            [68204] = {
                helpText = "Find Lost Mosswool 3 times and then wait for treasure to spawn",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 60, y = 25, title = "Mosswool Flower" }
                        }
                    }
                }
            },
            [68205] = {
                helpText = "Shared with other players, can take some time to respawn",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 63, y = 43, title = "Kobold Pickaxe" }
                        }
                    }
                }
            },
            [68206] = {
                helpText = "Find it on the shore",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 77, y = 24, title = "Jade Pearl" }
                        }
                    }
                }
            },
            [68207] = {
                helpText = "Underground",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 49, y = 61, title = "Shimmering Opal Lily" }
                        }
                    }
                }
            },
            [68208] = {
                helpText = "Shared with other players, can take some time to respawn",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 56, y = 61, title = "Infused Cinderbrew" }
                        }
                    }
                }
            },
            [68209] = {
                helpText = "Shared with other players, can take some time to respawn",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 59, y = 23, title = "Web-Wrapped Axe" }
                        }
                    }
                }
            },
        }
    },
    
    -- Achievement 40606: Flat Earthen
    [40606] = {
        helpText = "Get crushed by the machine in central Dornogal forge",
        waypoints = {
            {
                kind = "point",
                coordinates = {
                    { mapId = MapZones.TWW_ZONE_Dornogal, x = 50, y = 61, title = "Flat Earthen" }
                }
            }
        }
    },
    
    -- Achievement 40859: We're Here All Night
    [40859] = {
        helpText = "",
        waypoints = {
            {
                kind = "point",
                coordinates = {
                    { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 56, y = 51, title = "Theater Troupe location" }
                }
            }
        }
    },
    
    -- Achievement 40860: A Star of Dorn
    [40860] = {
        helpText = "Talk to NPCs at renown 3, 8, 14, and 21.",
        waypoints = {
            {
                kind = "point",
                coordinates = {
                    { mapId = MapZones.TWW_ZONE_IsleOfDorn, x = 57, y = 52, title = "Achievement NPCs" }
                }
            }
        }
    },
    
    -- Achievement 40504: Rocked to Sleep
    [40504] = {
        helpText = "",
        criteria = {
            [68684] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 58.7, y = 36.3, title = "Attwogaz" }
                        }
                    }
                }
            },
            [68682] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 41.3, y = 13.5, title = "Hathlaz" }
                        }
                    }
                }
            },
            [68685] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 39, y = 40.9, title = "Krattdaz" }
                        }
                    }
                }
            },
            [68686] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 51, y = 30, title = "Uisgaz" }
                        }
                    }
                }
            },
            [68687] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 44.4, y = 31.75, title = "Venedaz" }
                        }
                    }
                }
            },
            [68688] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 55, y = 93.5, title = "Merunth" }
                        }
                    }
                }
            },
            [68689] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 45.2, y = 49, title = "Varerko" }
                        }
                    }
                }
            },
            [68690] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 44.4, y = 70.6, title = "Alfritha" }
                        }
                    }
                }
            },
            [68691] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 61.3, y = 73.7, title = "Gundrig" }
                        }
                    }
                }
            },
            [68692] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 60, y = 55.75, title = "Sathilga" }
                        }
                    }
                }
            },
        }
    },
    
    -- Achievement 40837: Adventurer of The Ringing Deeps
    [40837] = {
        helpText = "",
        criteria = {
            [69623] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 67.0, y = 31.0, title = "Candleflyer Captain" }
                        }
                    }
                }
            },
            [69624] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 42.8, y = 35.0, title = "King Splash" }
                        }
                    }
                }
            },
            [69625] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 49.6, y = 66.2, title = "Aquellion" }
                        }
                    }
                }
            },
            [69626] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 57.2, y = 54.8, title = "Rampaging Blight" }
                        }
                    }
                }
            },
            [69627] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 66.8, y = 68.4, title = "Deathbound Husk" }
                        }
                    }
                }
            },
            [69628] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 47.6, y = 11.6, title = "Terror of the Forge" }
                        }
                    }
                }
            },
            [69629] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 52.0, y = 26.6, title = "Zilthara" }
                        }
                    }
                }
            },
            [69630] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 50.8, y = 46.6, title = "Cragmund" }
                        }
                    }
                }
            },
            [69631] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 71.6, y = 46.2, title = "Trungal" }
                        }
                    }
                }
            },
            [69632] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 41.6, y = 17.0, title = "Charmonger" }
                        }
                    }
                }
            },
            [69633] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 57.8, y = 38.6, title = "Coalesced Monstrosity" }
                        }
                    }
                }
            },
            [69634] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 52.6, y = 19.8, title = "Automaxor" }
                        }
                    }
                }
            },
            [69635] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 47.0, y = 46.8, title = "Kelpmire" }
                        }
                    }
                }
            },
            [69636] = {
                helpText = "Respawn can take up to 6 hours",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 55.8, y = 9.2, title = "Deepflayer Broodmother" }
                        }
                    }
                }
            },
            [69637] = {
                helpText = "Need to pull 5 levers, you need a group of 5 people",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 60.8, y = 76.6, title = "Lurker of the Deeps" },
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 49.5, y = 8.75, title = "Lever 1" },
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 54, y = 25.25, title = "Lever 2" },
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 57.5, y = 23.5, title = "Lever 3" },
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 62.75, y = 44.5, title = "Lever 4" },
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 59, y = 92.5, title = "Lever 5" }
                        }
                    }
                }
            },
            [69638] = {
                helpText = "General area, check WoWhead for more information",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 67.2, y = 46.2, title = "Spore-infused Shalewing" }
                        }
                    }
                }
            },
            [69639] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 66, y = 49.6, title = "Hungerer of the Deeps" }
                        }
                    }
                }
            },
            [69640] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 67.0, y = 52.6, title = "Disturbed Earthgorger" }
                        }
                    }
                }
            },
        }
    },
    
    -- Achievement 40724: Treasures of The Ringing Deeps
    [40724] = {
        helpText = "",
        criteria = {
            [69280] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 68.7, y = 40.8, title = "Cave entrance" },
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 68.9, y = 38.8, title = "Webbed Knapsack" }
                        }
                    }
                }
            },
            [69281] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 63.1, y = 63.1, title = "Cursed Pickaxe" }
                        }
                    }
                }
            },
            [69282] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 54.6, y = 14.2, title = "Cave entrance" },
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 55.4, y = 13.9, title = "Munderut's Forgotten Stash" }
                        }
                    }
                }
            },
            [69283] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 45.5, y = 17.5, title = "Discarded Toolbox" }
                        }
                    }
                }
            },
            [69304] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 66.2, y = 33.4, title = "Waterlogged Refuse" }
                        }
                    }
                }
            },
            [69307] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 59, y = 30.3, title = "Scary Dark Chest" }
                        }
                    }
                }
            },
            [69308] = {
                helpText = "Bluesberry Blast > Orange O-pocalypse > Oyster Outburst > Mangoro Mania",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 59, y = 64.4, title = "Kaja'Cola Machine" }
                        }
                    }
                }
            },
            [69311] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 48.25, y = 49, title = "Dislodged Blockage" }
                        }
                    }
                }
            },
            [69312] = {
                helpText = "",
                waypoints = {
                    {
                        kind = "point",
                        coordinates = {
                            { mapId = MapZones.TWW_ZONE_TheRingingDeeps, x = 49, y = 31.5, title = "Dusty Prospector's Chest" }
                        }
                    }
                }
            },
            [69313] = {
                helpText = "",
                waypoints = {}
            },
        }
    },
    
    -- Note: This file contains waypoint structures for achievements with criteria found in WorldSoulSearching.lua
    -- More achievements will be added as the file is parsed completely
    -- Achievements with only children (no criteria) are listed but don't have criteria sections
    -- Add waypoints and helpText as needed for each achievement/criteria
}
