function IsQuestCriteriaCompleted(achievementId, criteriaId)
    return C_QuestLog.IsQuestFlaggedCompleted(criteriaId)
end

RegisterCriteriaCompletionHandler(AchievementCriteriaTypes.CompletingAQuest, IsQuestCriteriaCompleted)