-- Waypoints for "The Flame Keeper" (1039) - Midsummer Fire Festival (event 341)
-- Part of What a Long, Strange Trip It's Been (2144)
-- Horde: The Fires of Azeroth (1036) - Flame Keeper (honor Horde flames)
-- Alliance: The Fires of Azeroth (1034) - Flame Warden (honor Alliance flames)
-- Coordinates from HandyNotes_SummerFestival (Ravendwyr)

WhatALongStrangeTripItsBeen_TheFlameKeeperWaypoints = {
    [1039] = {
        helpText = "The Flame Keeper: Complete The Fires of Azeroth (Horde) or The Fires of Azeroth (Alliance). Honor the bonfires in each zone during Midsummer Fire Festival.",
    },
    -- Horde: Flame Keeper (honor Horde flames)
    [1036] = {
        helpText = "The Fires of Azeroth (Horde): Honor the bonfires in Cataclysm, Eastern Kingdoms, Kalimdor, Northrend, and Outland.",
    },
    [6012] = {
        helpText = "Flame Keeper of Cataclysm (Horde): Honor bonfires in Deepholm, Hyjal, Twilight Highlands, Uldum, and Vashj'ir.",
        criteria = {
            [18197] = { helpText = "Deepholm.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Deepholm, x = 49.4, y = 51.32, title = "Deepholm, Temple of Earth" } } } } },
            [18198] = { helpText = "Hyjal.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_MountHyjal, x = 62.83, y = 22.71, title = "Hyjal, Nordrassil" } } } } },
            [18202] = { helpText = "Twilight Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_TwilightHighlands, x = 53.12, y = 46.16, title = "Twilight Highlands, Bloodgulch" } } } } },
            [18203] = { helpText = "Uldum.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Uldum, x = 53.16, y = 34.54, title = "Uldum, Ramkahen" } } } } },
            [18199] = { helpText = "Vashj'ir.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Vashjir, x = 49.35, y = 41.99, title = "Vashj'ir, Silver Tide Hollow" } } } } },
        },
    },
    [1025] = {
        helpText = "Flame Keeper of Eastern Kingdoms (Horde): Honor bonfires in Arathi, Badlands, Blasted Lands, Burning Steppes, Eversong, Ghostlands, Hillsbrad, Northern Stranglethorn, Silverpine, Swamp of Sorrows, Cape of Stranglethorn, Hinterlands, Tirisfal, Western Plaguelands.",
        criteria = {
            [3101] = { helpText = "Arathi Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ArathiHighlands, x = 69.39, y = 42.59, title = "Arathi Highlands, Hammerfall" } } } } },
            [3102] = { helpText = "Badlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Badlands, x = 23.09, y = 37.45, title = "Badlands, New Kargath" } } } } },
            [23464] = { helpText = "Blasted Lands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BlastedLands, x = 46.22, y = 13.79, title = "Blasted Lands, Dreadmaul Hold" } } } } },
            [3103] = { helpText = "Burning Steppes.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BurningSteppes, x = 51.11, y = 29.22, title = "Burning Steppes, Flame Crest" } } } } },
            [3104] = { helpText = "Eversong Woods.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_EversongWoods, x = 46.41, y = 50.6, title = "Eversong Woods, Falconwing Square" } } } } },
            [3105] = { helpText = "Ghostlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ghostlands, x = 46.89, y = 26.33, title = "Ghostlands, Tranquillien" } } } } },
            [3106] = { helpText = "Hillsbrad Foothills.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_HillsbradFoothills, x = 54.65, y = 50.09, title = "Hillsbrad Foothills, Tarren Mill" } } } } },
            [17012] = { helpText = "Northern Stranglethorn.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernStranglethorn, x = 40.58, y = 50.93, title = "Northern Stranglethorn, Grom'gol Base Camp" } } } } },
            [3107] = { helpText = "Silverpine Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SilverpineForest, x = 49.63, y = 38.2, title = "Silverpine Forest, The Sepulcher" } } } } },
            [3109] = { helpText = "Swamp of Sorrows.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SwampOfSorrows, x = 76.36, y = 13.76, title = "Swamp of Sorrows, Bogpaddle" } } } } },
            [3108] = { helpText = "The Cape of Stranglethorn.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheCapeOfStranglethorn, x = 50.41, y = 70.37, title = "The Cape of Stranglethorn, Wild Shore" } } } } },
            [3110] = { helpText = "The Hinterlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheHinterlands, x = 76.62, y = 74.97, title = "The Hinterlands, Revantusk Village" } } } } },
            [3111] = { helpText = "Tirisfal Glades.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TirisfalGlades, x = 57.23, y = 51.77, title = "Tirisfal Glades, Brill" } } } } },
            [23465] = { helpText = "Western Plaguelands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_WesternPlaguelands, x = 29.16, y = 57.35, title = "Western Plaguelands, The Bulwark" } } } } },
        },
    },
    [1026] = {
        helpText = "Flame Keeper of Kalimdor (Horde): Honor bonfires in Ashenvale, Azshara, Desolace, Durotar, Dustwallow, Feralas, Mulgore, Northern Barrens, Silithus, Southern Barrens, Stonetalon, Tanaris, Un'Goro, Winterspring.",
        criteria = {
            [3112] = { helpText = "Ashenvale.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 51.34, y = 66.15, title = "Ashenvale, Silverwind Refuge" } } } } },
            [23471] = { helpText = "Azshara.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Azshara, x = 60.79, y = 53.48, title = "Azshara, Bilgewater Harbour" } } } } },
            [3113] = { helpText = "Desolace.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Desolace, x = 26.13, y = 76.9, title = "Desolace, Shadowprey Village" } } } } },
            [3114] = { helpText = "Durotar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Durotar, x = 52.25, y = 47.39, title = "Durotar, Razor Hill" } } } } },
            [3115] = { helpText = "Dustwallow Marsh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DustwallowMarsh, x = 33.43, y = 30.92, title = "Dustwallow Marsh, Brackenwall Village" } } } } },
            [3116] = { helpText = "Feralas.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 72.38, y = 47.8, title = "Feralas, Camp Mojache" } } } } },
            [3117] = { helpText = "Mulgore.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Mulgore, x = 51.82, y = 59.24, title = "Mulgore, Bloodhoof Village" } } } } },
            [3121] = { helpText = "Northern Barrens.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernBarrens, x = 49.97, y = 54.62, title = "Northern Barrens, The Crossroads" } } } } },
            [3118] = { helpText = "Silithus.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Silithus, x = 50.84, y = 41.3, title = "Silithus, Cenarion Hold" } } } } },
            [17015] = { helpText = "Southern Barrens.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 40.86, y = 67.79, title = "Southern Barrens, Desolation Hold" } } } } },
            [3119] = { helpText = "Stonetalon Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 52.92, y = 62.46, title = "Stonetalon Mountains, Sun Rock Retreat" } } } } },
            [3120] = { helpText = "Tanaris.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 49.82, y = 27.86, title = "Tanaris, Gadgetzan" } } } } },
            [23474] = { helpText = "Un'Goro Crater.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_UnGoroCrater, x = 56.32, y = 66.36, title = "Un'Goro Crater, Marshal's Stand" } } } } },
            [3123] = { helpText = "Winterspring.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Winterspring, x = 58.14, y = 47.51, title = "Winterspring, Everlook" } } } } },
        },
    },
    [6009] = {
        helpText = "Flame Keeper of Northrend (Horde): Honor bonfires in Borean Tundra, Crystalsong, Dragonblight, Grizzly Hills, Howling Fjord, Sholazar Basin, Storm Peaks, Zul'Drak.",
        criteria = {
            [18179] = { helpText = "Borean Tundra.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_BoreanTundra, x = 51.14, y = 11.54, title = "Borean Tundra, Bor'gorok Outpost" } } } } },
            [18180] = { helpText = "Crystalsong Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_CrystalsongForest, x = 79.97, y = 53.24, title = "Crystalsong Forest, Sunreaver's Command" } } } } },
            [18181] = { helpText = "Dragonblight.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_Dragonblight, x = 38.26, y = 48.48, title = "Dragonblight, Agmar's Hammer" } } } } },
            [18182] = { helpText = "Grizzly Hills.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_GrizzlyHills, x = 19.38, y = 61.14, title = "Grizzly Hills, Conquest Hold" } } } } },
            [18183] = { helpText = "Howling Fjord.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_HowlingFjord, x = 48.62, y = 13.15, title = "Howling Fjord, Camp Winterhoof" } } } } },
            [18184] = { helpText = "Sholazar Basin.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_SholazarBasin, x = 47.06, y = 61.57, title = "Sholazar Basin, River's Heart" } } } } },
            [18185] = { helpText = "Storm Peaks.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_TheStormPeaks, x = 40.28, y = 85.35, title = "Storm Peaks, K3" } } } } },
            [18186] = { helpText = "Zul'Drak.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_ZulDrak, x = 43.37, y = 71.76, title = "Zul'Drak, The Argent Stand" } } } } },
        },
    },
    [1027] = {
        helpText = "Flame Keeper of Outland (Horde): Honor bonfires in Blade's Edge, Hellfire Peninsula, Nagrand, Netherstorm, Shadowmoon Valley, Terokkar Forest, Zangarmarsh.",
        criteria = {
            [3124] = { helpText = "Blade's Edge Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 49.91, y = 58.67, title = "Blade's Edge Mountains, Thunderlord Stronghold" } } } } },
            [3125] = { helpText = "Hellfire Peninsula.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_HellfirePeninsula, x = 57.1, y = 42.11, title = "Hellfire Peninsula, Thrallmar" } } } } },
            [3126] = { helpText = "Nagrand.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Nagrand, x = 50.91, y = 34.15, title = "Nagrand, Garadar" } } } } },
            [3127] = { helpText = "Netherstorm.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Netherstorm, x = 32.11, y = 68.33, title = "Netherstorm, Area 52" } } } } },
            [3128] = { helpText = "Shadowmoon Valley.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_ShadowmoonValley, x = 33.4, y = 30.54, title = "Shadowmoon Valley, Shadowmoon Village" } } } } },
            [3129] = { helpText = "Terokkar Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_TerokkarForest, x = 52.01, y = 42.87, title = "Terokkar Forest, Stonebreaker Hold" } } } } },
            [3130] = { helpText = "Zangarmarsh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Zangarmarsh, x = 35.43, y = 51.62, title = "Zangarmarsh, Zabra'jin" } } } } },
        },
    },
    -- Alliance: Flame Warden (honor Alliance flames)
    [1034] = {
        helpText = "The Fires of Azeroth (Alliance): Honor the bonfires in Cataclysm, Eastern Kingdoms, Kalimdor, Northrend, and Outland.",
    },
    [6011] = {
        helpText = "Flame Warden of Cataclysm (Alliance): Honor bonfires in Deepholm, Hyjal, Twilight Highlands, Uldum, and Vashj'ir.",
        criteria = {
            [18197] = { helpText = "Deepholm.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Deepholm, x = 49.4, y = 51.32, title = "Deepholm, Temple of Earth" } } } } },
            [18198] = { helpText = "Hyjal.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_MountHyjal, x = 62.83, y = 22.71, title = "Hyjal, Nordrassil" } } } } },
            [18202] = { helpText = "Twilight Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_TwilightHighlands, x = 47.26, y = 28.96, title = "Twilight Highlands, Thundermar" } } } } },
            [18203] = { helpText = "Uldum.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Uldum, x = 53.6, y = 31.84, title = "Uldum, Ramkahen" } } } } },
            [18199] = { helpText = "Vashj'ir.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Vashjir, x = 49.35, y = 41.99, title = "Vashj'ir, Silver Tide Hollow" } } } } },
        },
    },
    [1022] = {
        helpText = "Flame Warden of Eastern Kingdoms (Alliance): Honor bonfires in Arathi, Badlands, Blasted Lands, Burning Steppes, Dun Morogh, Duskwood, Elwynn, Loch Modan, Northern Stranglethorn, Redridge, Swamp of Sorrows, Cape of Stranglethorn, Hinterlands, Western Plaguelands, Westfall, Wetlands.",
        criteria = {
            [3161] = { helpText = "Arathi Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ArathiHighlands, x = 44.3, y = 46.03, title = "Arathi Highlands, Refuge Pointe" } } } } },
            [23512] = { helpText = "Badlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Badlands, x = 24.1, y = 37.22, title = "Badlands, Dragon's Mouth" } } } } },
            [3162] = { helpText = "Blasted Lands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BlastedLands, x = 55.53, y = 14.88, title = "Blasted Lands, Nethergarde Keep" } } } } },
            [3163] = { helpText = "Burning Steppes.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BurningSteppes, x = 68.58, y = 60.06, title = "Burning Steppes, Morgan's Vigil" } } } } },
            [3164] = { helpText = "Dun Morogh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DunMorogh, x = 53.8, y = 45.23, title = "Dun Morogh, Kharanos" } } } } },
            [3165] = { helpText = "Duskwood.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Duskwood, x = 73.69, y = 54.62, title = "Duskwood, Darkshire" } } } } },
            [3166] = { helpText = "Elwynn Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ElwynnForest, x = 43.47, y = 62.63, title = "Elwynn Forest, Goldshire" } } } } },
            [3168] = { helpText = "Loch Modan.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_LochModan, x = 32.55, y = 40.95, title = "Loch Modan, Thelsamar" } } } } },
            [17011] = { helpText = "Northern Stranglethorn.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernStranglethorn, x = 51.65, y = 63.56, title = "Northern Stranglethorn, Fort Livingston" } } } } },
            [3169] = { helpText = "Redridge Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_RedridgeMountains, x = 24.9, y = 53.38, title = "Redridge Mountains, Lakeshire" } } } } },
            [23511] = { helpText = "Swamp of Sorrows.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SwampOfSorrows, x = 70.24, y = 15.73, title = "Swamp of Sorrows, Bogpaddle" } } } } },
            [3170] = { helpText = "The Cape of Stranglethorn.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheCapeOfStranglethorn, x = 51.97, y = 67.64, title = "The Cape of Stranglethorn, Wild Shore" } } } } },
            [3171] = { helpText = "The Hinterlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheHinterlands, x = 14.34, y = 50.07, title = "The Hinterlands, Aerie Peak" } } } } },
            [3172] = { helpText = "Western Plaguelands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_WesternPlaguelands, x = 43.48, y = 82.33, title = "Western Plaguelands, Chillwind Camp" } } } } },
            [3173] = { helpText = "Westfall.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Westfall, x = 44.76, y = 62.06, title = "Westfall, Moonbrook" } } } } },
            [5266] = { helpText = "Wetlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Wetlands, x = 13.46, y = 47.06, title = "Wetlands, Menethil Harbour" } } } } },
        },
    },
    [1023] = {
        helpText = "Flame Warden of Kalimdor (Alliance): Honor bonfires in Ashenvale, Azuremyst, Bloodmyst, Darkshore, Desolace, Dustwallow, Feralas, Silithus, Southern Barrens, Stonetalon, Tanaris, Teldrassil, Un'Goro, Winterspring.",
        criteria = {
            [3174] = { helpText = "Ashenvale.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 86.94, y = 41.86, title = "Ashenvale, Forest Song" } } } } },
            [3175] = { helpText = "Azuremyst Isle.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_AzuremystIsle, x = 44.48, y = 52.51, title = "Azuremyst Isle, Azure Watch" } } } } },
            [3176] = { helpText = "Bloodmyst Isle.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BloodmystIsle, x = 55.82, y = 67.89, title = "Bloodmyst Isle, Blood Watch" } } } } },
            [3177] = { helpText = "Darkshore.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Darkshore, x = 48.72, y = 22.65, title = "Darkshore, Lor'danel" } } } } },
            [3178] = { helpText = "Desolace.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Desolace, x = 66.12, y = 17.09, title = "Desolace, Nijel's Point" } } } } },
            [3179] = { helpText = "Dustwallow Marsh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DustwallowMarsh, x = 61.82, y = 40.46, title = "Dustwallow Marsh, Theramore Isle" } } } } },
            [3180] = { helpText = "Feralas.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 46.82, y = 43.7, title = "Feralas, Feathermoon Stronghold" } } } } },
            [3181] = { helpText = "Silithus.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Silithus, x = 60.31, y = 33.51, title = "Silithus, Cenarion Hold" } } } } },
            [17017] = { helpText = "Southern Barrens.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 48.33, y = 72.23, title = "Southern Barrens, Fort Triumph" } } } } },
            [23516] = { helpText = "Stonetalon Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 49.3, y = 51.33, title = "Stonetalon Mountains, Mirkfallon Lake" } } } } },
            [3182] = { helpText = "Tanaris.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 52.64, y = 30.26, title = "Tanaris, Gadgetzan" } } } } },
            [3183] = { helpText = "Teldrassil.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Teldrassil, x = 54.88, y = 52.77, title = "Teldrassil, Dolanaar" } } } } },
            [23515] = { helpText = "Un'Goro Crater.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_UnGoroCrater, x = 59.86, y = 63.24, title = "Un'Goro Crater, Marshal's Stand" } } } } },
            [3185] = { helpText = "Winterspring.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Winterspring, x = 61.24, y = 47.25, title = "Winterspring, Everlook" } } } } },
        },
    },
    [6008] = {
        helpText = "Flame Warden of Northrend (Alliance): Honor bonfires in Borean Tundra, Crystalsong, Dragonblight, Grizzly Hills, Howling Fjord, Sholazar Basin, Storm Peaks, Zul'Drak.",
        criteria = {
            [18187] = { helpText = "Borean Tundra.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_BoreanTundra, x = 55.1, y = 19.95, title = "Borean Tundra, Fizzcrank Airstrip" } } } } },
            [18188] = { helpText = "Crystalsong Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_CrystalsongForest, x = 78.19, y = 74.95, title = "Crystalsong Forest, Windrunner's Overlook" } } } } },
            [18189] = { helpText = "Dragonblight.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_Dragonblight, x = 75.04, y = 43.79, title = "Dragonblight, Wintergarde Keep" } } } } },
            [18190] = { helpText = "Grizzly Hills.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_GrizzlyHills, x = 34.26, y = 60.45, title = "Grizzly Hills, Amberpine Lodge" } } } } },
            [18191] = { helpText = "Howling Fjord.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_HowlingFjord, x = 57.81, y = 16.11, title = "Howling Fjord, Fort Wildervar" } } } } },
            [18192] = { helpText = "Sholazar Basin.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_SholazarBasin, x = 47.86, y = 66.16, title = "Sholazar Basin, River's Heart" } } } } },
            [18193] = { helpText = "Storm Peaks.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_TheStormPeaks, x = 41.44, y = 86.69, title = "Storm Peaks, K3" } } } } },
            [18194] = { helpText = "Zul'Drak.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_ZulDrak, x = 40.38, y = 61.3, title = "Zul'Drak, The Argent Stand" } } } } },
        },
    },
    [1024] = {
        helpText = "Flame Warden of Outland (Alliance): Honor bonfires in Blade's Edge, Hellfire Peninsula, Nagrand, Netherstorm, Shadowmoon Valley, Terokkar Forest, Zangarmarsh.",
        criteria = {
            [3186] = { helpText = "Blade's Edge Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 41.57, y = 65.9, title = "Blade's Edge Mountains, Sylvanaar" } } } } },
            [3187] = { helpText = "Hellfire Peninsula.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_HellfirePeninsula, x = 62.17, y = 58.29, title = "Hellfire Peninsula, Honor Hold" } } } } },
            [3188] = { helpText = "Nagrand.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Nagrand, x = 49.61, y = 69.46, title = "Nagrand, Telaar" } } } } },
            [3189] = { helpText = "Netherstorm.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Netherstorm, x = 31.21, y = 62.66, title = "Netherstorm, Area 52" } } } } },
            [3190] = { helpText = "Shadowmoon Valley.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_ShadowmoonValley, x = 39.62, y = 54.64, title = "Shadowmoon Valley, Wildhammer Stronghold" } } } } },
            [3191] = { helpText = "Terokkar Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_TerokkarForest, x = 54.06, y = 55.52, title = "Terokkar Forest, Allerian Stronghold" } } } } },
            [3192] = { helpText = "Zangarmarsh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Zangarmarsh, x = 68.79, y = 51.95, title = "Zangarmarsh, Telredor" } } } } },
        },
    },
    -- Desecration of the Alliance (1037) - Horde extinguishes Alliance flames (same locations as Alliance Flame Warden)
    [1037] = {
        helpText = "Desecration of the Alliance: Extinguish the Alliance bonfires in each zone during Midsummer Fire Festival. (Horde only)",
    },
    [6014] = {
        helpText = "Extinguishing the Cataclysm (Alliance flames): Twilight Highlands and Uldum.",
        criteria = {
            [18210] = { helpText = "Twilight Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_TwilightHighlands, x = 47.26, y = 28.96, title = "Twilight Highlands, Thundermar" } } } } },
            [18211] = { helpText = "Uldum.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Uldum, x = 53.6, y = 31.84, title = "Uldum, Ramkahen" } } } } },
        },
    },
    [1031] = {
        helpText = "Extinguishing Eastern Kingdoms (Alliance flames): Arathi through Wetlands.",
        criteria = {
            [3161] = { helpText = "Arathi Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ArathiHighlands, x = 44.3, y = 46.03, title = "Arathi Highlands, Refuge Pointe" } } } } },
            [23512] = { helpText = "Badlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Badlands, x = 24.1, y = 37.22, title = "Badlands, Dragon's Mouth" } } } } },
            [3162] = { helpText = "Blasted Lands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BlastedLands, x = 55.53, y = 14.88, title = "Blasted Lands, Nethergarde Keep" } } } } },
            [3163] = { helpText = "Burning Steppes.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BurningSteppes, x = 68.58, y = 60.06, title = "Burning Steppes, Morgan's Vigil" } } } } },
            [3164] = { helpText = "Dun Morogh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DunMorogh, x = 53.8, y = 45.23, title = "Dun Morogh, Kharanos" } } } } },
            [3165] = { helpText = "Duskwood.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Duskwood, x = 73.69, y = 54.62, title = "Duskwood, Darkshire" } } } } },
            [3166] = { helpText = "Elwynn Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ElwynnForest, x = 43.47, y = 62.63, title = "Elwynn Forest, Goldshire" } } } } },
            [3168] = { helpText = "Loch Modan.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_LochModan, x = 32.55, y = 40.95, title = "Loch Modan, Thelsamar" } } } } },
            [17011] = { helpText = "Northern Stranglethorn.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernStranglethorn, x = 51.65, y = 63.56, title = "Northern Stranglethorn, Fort Livingston" } } } } },
            [3169] = { helpText = "Redridge Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_RedridgeMountains, x = 24.9, y = 53.38, title = "Redridge Mountains, Lakeshire" } } } } },
            [23511] = { helpText = "Swamp of Sorrows.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SwampOfSorrows, x = 70.24, y = 15.73, title = "Swamp of Sorrows, Bogpaddle" } } } } },
            [3170] = { helpText = "The Cape of Stranglethorn.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheCapeOfStranglethorn, x = 51.97, y = 67.64, title = "The Cape of Stranglethorn, Wild Shore" } } } } },
            [3171] = { helpText = "The Hinterlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheHinterlands, x = 14.34, y = 50.07, title = "The Hinterlands, Aerie Peak" } } } } },
            [3172] = { helpText = "Western Plaguelands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_WesternPlaguelands, x = 43.48, y = 82.33, title = "Western Plaguelands, Chillwind Camp" } } } } },
            [3173] = { helpText = "Westfall.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Westfall, x = 44.76, y = 62.06, title = "Westfall, Moonbrook" } } } } },
            [5266] = { helpText = "Wetlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Wetlands, x = 13.46, y = 47.06, title = "Wetlands, Menethil Harbour" } } } } },
        },
    },
    [1032] = {
        helpText = "Extinguishing Kalimdor (Alliance flames): Ashenvale through Winterspring.",
        criteria = {
            [3174] = { helpText = "Ashenvale.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 86.94, y = 41.86, title = "Ashenvale, Forest Song" } } } } },
            [3175] = { helpText = "Azuremyst Isle.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_AzuremystIsle, x = 44.48, y = 52.51, title = "Azuremyst Isle, Azure Watch" } } } } },
            [3176] = { helpText = "Bloodmyst Isle.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BloodmystIsle, x = 55.82, y = 67.89, title = "Bloodmyst Isle, Blood Watch" } } } } },
            [3177] = { helpText = "Darkshore.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Darkshore, x = 48.72, y = 22.65, title = "Darkshore, Lor'danel" } } } } },
            [3178] = { helpText = "Desolace.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Desolace, x = 66.12, y = 17.09, title = "Desolace, Nijel's Point" } } } } },
            [3179] = { helpText = "Dustwallow Marsh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DustwallowMarsh, x = 61.82, y = 40.46, title = "Dustwallow Marsh, Theramore Isle" } } } } },
            [3180] = { helpText = "Feralas.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 46.82, y = 43.7, title = "Feralas, Feathermoon Stronghold" } } } } },
            [3181] = { helpText = "Silithus.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Silithus, x = 60.31, y = 33.51, title = "Silithus, Cenarion Hold" } } } } },
            [17017] = { helpText = "Southern Barrens.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 48.33, y = 72.23, title = "Southern Barrens, Fort Triumph" } } } } },
            [23516] = { helpText = "Stonetalon Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 49.3, y = 51.33, title = "Stonetalon Mountains, Mirkfallon Lake" } } } } },
            [3182] = { helpText = "Tanaris.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 52.64, y = 30.26, title = "Tanaris, Gadgetzan" } } } } },
            [3183] = { helpText = "Teldrassil.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Teldrassil, x = 54.88, y = 52.77, title = "Teldrassil, Dolanaar" } } } } },
            [23515] = { helpText = "Un'Goro Crater.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_UnGoroCrater, x = 59.86, y = 63.24, title = "Un'Goro Crater, Marshal's Stand" } } } } },
            [3185] = { helpText = "Winterspring.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Winterspring, x = 61.24, y = 47.25, title = "Winterspring, Everlook" } } } } },
        },
    },
    [6010] = {
        helpText = "Extinguishing Northrend (Alliance flames): Borean Tundra through Crystalsong Forest.",
        criteria = {
            [18189] = { helpText = "Dragonblight.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_Dragonblight, x = 75.04, y = 43.79, title = "Dragonblight, Wintergarde Keep" } } } } },
            [18187] = { helpText = "Borean Tundra.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_BoreanTundra, x = 55.1, y = 19.95, title = "Borean Tundra, Fizzcrank Airstrip" } } } } },
            [18191] = { helpText = "Howling Fjord.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_HowlingFjord, x = 57.81, y = 16.11, title = "Howling Fjord, Fort Wildervar" } } } } },
            [18192] = { helpText = "Sholazar Basin.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_SholazarBasin, x = 47.86, y = 66.16, title = "Sholazar Basin, River's Heart" } } } } },
            [18193] = { helpText = "Storm Peaks.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_TheStormPeaks, x = 41.44, y = 86.69, title = "Storm Peaks, K3" } } } } },
            [18194] = { helpText = "Zul'Drak.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_ZulDrak, x = 40.38, y = 61.3, title = "Zul'Drak, The Argent Stand" } } } } },
            [18190] = { helpText = "Grizzly Hills.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_GrizzlyHills, x = 34.26, y = 60.45, title = "Grizzly Hills, Amberpine Lodge" } } } } },
            [18188] = { helpText = "Crystalsong Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_CrystalsongForest, x = 78.19, y = 74.95, title = "Crystalsong Forest, Windrunner's Overlook" } } } } },
        },
    },
    [1033] = {
        helpText = "Extinguishing Outland (Alliance flames): Blade's Edge through Zangarmarsh.",
        criteria = {
            [3186] = { helpText = "Blade's Edge Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 41.57, y = 65.9, title = "Blade's Edge Mountains, Sylvanaar" } } } } },
            [3187] = { helpText = "Hellfire Peninsula.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_HellfirePeninsula, x = 62.17, y = 58.29, title = "Hellfire Peninsula, Honor Hold" } } } } },
            [3188] = { helpText = "Nagrand.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Nagrand, x = 49.61, y = 69.46, title = "Nagrand, Telaar" } } } } },
            [3189] = { helpText = "Netherstorm.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Netherstorm, x = 31.21, y = 62.66, title = "Netherstorm, Area 52" } } } } },
            [3190] = { helpText = "Shadowmoon Valley.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_ShadowmoonValley, x = 39.62, y = 54.64, title = "Shadowmoon Valley, Wildhammer Stronghold" } } } } },
            [3191] = { helpText = "Terokkar Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_TerokkarForest, x = 54.06, y = 55.52, title = "Terokkar Forest, Allerian Stronghold" } } } } },
            [3192] = { helpText = "Zangarmarsh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Zangarmarsh, x = 68.79, y = 51.95, title = "Zangarmarsh, Telredor" } } } } },
        },
    },
    -- Desecration of the Horde (1035) - Alliance extinguishes Horde flames (same locations as Horde Flame Keeper)
    [1035] = {
        helpText = "Desecration of the Horde: Extinguish the Horde bonfires in each zone during Midsummer Fire Festival. (Alliance only)",
    },
    [6013] = {
        helpText = "Extinguishing the Cataclysm (Horde flames): Deepholm, Hyjal, Twilight Highlands, Uldum, Vashj'ir.",
        criteria = {
            [18199] = { helpText = "Vashj'ir.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Vashjir, x = 49.35, y = 41.99, title = "Vashj'ir, Silver Tide Hollow" } } } } },
            [18202] = { helpText = "Twilight Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_TwilightHighlands, x = 53.12, y = 46.16, title = "Twilight Highlands, Bloodgulch" } } } } },
            [18198] = { helpText = "Hyjal.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_MountHyjal, x = 62.83, y = 22.71, title = "Hyjal, Nordrassil" } } } } },
            [18197] = { helpText = "Deepholm.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Deepholm, x = 49.4, y = 51.32, title = "Deepholm, Temple of Earth" } } } } },
            [18203] = { helpText = "Uldum.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Uldum, x = 53.16, y = 34.54, title = "Uldum, Ramkahen" } } } } },
        },
    },
    [1028] = {
        helpText = "Extinguishing Eastern Kingdoms (Horde flames): Arathi through Western Plaguelands.",
        criteria = {
            [3101] = { helpText = "Arathi Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ArathiHighlands, x = 69.39, y = 42.59, title = "Arathi Highlands, Hammerfall" } } } } },
            [3102] = { helpText = "Badlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Badlands, x = 23.09, y = 37.45, title = "Badlands, New Kargath" } } } } },
            [23464] = { helpText = "Blasted Lands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BlastedLands, x = 46.22, y = 13.79, title = "Blasted Lands, Dreadmaul Hold" } } } } },
            [3103] = { helpText = "Burning Steppes.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BurningSteppes, x = 51.11, y = 29.22, title = "Burning Steppes, Flame Crest" } } } } },
            [3104] = { helpText = "Eversong Woods.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_EversongWoods, x = 46.41, y = 50.6, title = "Eversong Woods, Falconwing Square" } } } } },
            [3105] = { helpText = "Ghostlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ghostlands, x = 46.89, y = 26.33, title = "Ghostlands, Tranquillien" } } } } },
            [3106] = { helpText = "Hillsbrad Foothills.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_HillsbradFoothills, x = 54.65, y = 50.09, title = "Hillsbrad Foothills, Tarren Mill" } } } } },
            [17012] = { helpText = "Northern Stranglethorn.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernStranglethorn, x = 40.58, y = 50.93, title = "Northern Stranglethorn, Grom'gol Base Camp" } } } } },
            [3107] = { helpText = "Silverpine Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SilverpineForest, x = 49.63, y = 38.2, title = "Silverpine Forest, The Sepulcher" } } } } },
            [3109] = { helpText = "Swamp of Sorrows.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SwampOfSorrows, x = 76.36, y = 13.76, title = "Swamp of Sorrows, Bogpaddle" } } } } },
            [3108] = { helpText = "The Cape of Stranglethorn.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheCapeOfStranglethorn, x = 50.41, y = 70.37, title = "The Cape of Stranglethorn, Wild Shore" } } } } },
            [3110] = { helpText = "The Hinterlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheHinterlands, x = 76.62, y = 74.97, title = "The Hinterlands, Revantusk Village" } } } } },
            [3111] = { helpText = "Tirisfal Glades.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TirisfalGlades, x = 57.23, y = 51.77, title = "Tirisfal Glades, Brill" } } } } },
            [23465] = { helpText = "Western Plaguelands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_WesternPlaguelands, x = 29.16, y = 57.35, title = "Western Plaguelands, The Bulwark" } } } } },
        },
    },
    [1029] = {
        helpText = "Extinguishing Kalimdor (Horde flames): Ashenvale through Winterspring.",
        criteria = {
            [3112] = { helpText = "Ashenvale.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 51.34, y = 66.15, title = "Ashenvale, Silverwind Refuge" } } } } },
            [23471] = { helpText = "Azshara.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Azshara, x = 60.79, y = 53.48, title = "Azshara, Bilgewater Harbour" } } } } },
            [3113] = { helpText = "Desolace.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Desolace, x = 26.13, y = 76.9, title = "Desolace, Shadowprey Village" } } } } },
            [3114] = { helpText = "Durotar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Durotar, x = 52.25, y = 47.39, title = "Durotar, Razor Hill" } } } } },
            [3115] = { helpText = "Dustwallow Marsh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DustwallowMarsh, x = 33.43, y = 30.92, title = "Dustwallow Marsh, Brackenwall Village" } } } } },
            [3116] = { helpText = "Feralas.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 72.38, y = 47.8, title = "Feralas, Camp Mojache" } } } } },
            [3117] = { helpText = "Mulgore.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Mulgore, x = 51.82, y = 59.24, title = "Mulgore, Bloodhoof Village" } } } } },
            [3121] = { helpText = "Northern Barrens.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernBarrens, x = 49.97, y = 54.62, title = "Northern Barrens, The Crossroads" } } } } },
            [3118] = { helpText = "Silithus.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Silithus, x = 50.84, y = 41.3, title = "Silithus, Cenarion Hold" } } } } },
            [17015] = { helpText = "Southern Barrens.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 40.86, y = 67.79, title = "Southern Barrens, Desolation Hold" } } } } },
            [3119] = { helpText = "Stonetalon Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 52.92, y = 62.46, title = "Stonetalon Mountains, Sun Rock Retreat" } } } } },
            [3120] = { helpText = "Tanaris.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 49.82, y = 27.86, title = "Tanaris, Gadgetzan" } } } } },
            [23474] = { helpText = "Un'Goro Crater.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_UnGoroCrater, x = 56.32, y = 66.36, title = "Un'Goro Crater, Marshal's Stand" } } } } },
            [3123] = { helpText = "Winterspring.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Winterspring, x = 58.14, y = 47.51, title = "Winterspring, Everlook" } } } } },
        },
    },
    [6007] = {
        helpText = "Extinguishing Northrend (Horde flames): Borean Tundra through Crystalsong Forest.",
        criteria = {
            [18181] = { helpText = "Dragonblight.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_Dragonblight, x = 38.26, y = 48.48, title = "Dragonblight, Agmar's Hammer" } } } } },
            [18179] = { helpText = "Borean Tundra.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_BoreanTundra, x = 51.14, y = 11.54, title = "Borean Tundra, Bor'gorok Outpost" } } } } },
            [18183] = { helpText = "Howling Fjord.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_HowlingFjord, x = 48.62, y = 13.15, title = "Howling Fjord, Camp Winterhoof" } } } } },
            [18184] = { helpText = "Sholazar Basin.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_SholazarBasin, x = 47.06, y = 61.57, title = "Sholazar Basin, River's Heart" } } } } },
            [18185] = { helpText = "Storm Peaks.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_TheStormPeaks, x = 40.28, y = 85.35, title = "Storm Peaks, K3" } } } } },
            [18186] = { helpText = "Zul'Drak.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_ZulDrak, x = 43.37, y = 71.76, title = "Zul'Drak, The Argent Stand" } } } } },
            [18182] = { helpText = "Grizzly Hills.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_GrizzlyHills, x = 19.38, y = 61.14, title = "Grizzly Hills, Conquest Hold" } } } } },
            [18180] = { helpText = "Crystalsong Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_CrystalsongForest, x = 79.97, y = 53.24, title = "Crystalsong Forest, Sunreaver's Command" } } } } },
        },
    },
    [1030] = {
        helpText = "Extinguishing Outland (Horde flames): Blade's Edge through Zangarmarsh.",
        criteria = {
            [3124] = { helpText = "Blade's Edge Mountains.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 49.91, y = 58.67, title = "Blade's Edge Mountains, Thunderlord Stronghold" } } } } },
            [3125] = { helpText = "Hellfire Peninsula.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_HellfirePeninsula, x = 57.1, y = 42.11, title = "Hellfire Peninsula, Thrallmar" } } } } },
            [3126] = { helpText = "Nagrand.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Nagrand, x = 50.91, y = 34.15, title = "Nagrand, Garadar" } } } } },
            [3127] = { helpText = "Netherstorm.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Netherstorm, x = 32.11, y = 68.33, title = "Netherstorm, Area 52" } } } } },
            [3128] = { helpText = "Shadowmoon Valley.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_ShadowmoonValley, x = 33.4, y = 30.54, title = "Shadowmoon Valley, Shadowmoon Village" } } } } },
            [3129] = { helpText = "Terokkar Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_TerokkarForest, x = 52.01, y = 42.87, title = "Terokkar Forest, Stonebreaker Hold" } } } } },
            [3130] = { helpText = "Zangarmarsh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Zangarmarsh, x = 35.43, y = 51.62, title = "Zangarmarsh, Zabra'jin" } } } } },
        },
    },
}
