-- Waypoints for "To Honor One's Elders" (913) - Lunar Festival (event 327)
-- Part of What a Long, Strange Trip It's Been (2144)

WhatALongStrangeTripItsBeen_ToHonorOnesEldersWaypoints = {
    [2144] = {
        helpText = "Complete all 8 world event meta achievements: To Honor One's Elders (Lunar Festival), Fool For Love (Love is in the Air), Noble Gardener (Noblegarden), For the Children (Children's Week), The Flame Keeper (Midsummer), Brewmaster (Brewfest), Hallowed Be Thy Name (Hallow's End), Merrymaker (Winter Veil). Reward: Violet Proto-Drake.",
    },
    [913] = {
        helpText = "To Honor One's Elders: Complete all Lunar Festival elder achievements. Visit elders in Eastern Kingdoms, Kalimdor, Northrend, Cataclysm zones, dungeons, and capital cities during Lunar Festival (event 327). Use the waypoint buttons on each sub-achievement to add elder locations to your map.",
    },
    [6006] = {
        helpText = "Visit all 9 Cataclysm zone elders during Lunar Festival. Zones: Mount Hyjal, Uldum, Twilight Highlands, Vashj'ir, Deepholm, Temple of Earth (instance).",
        criteria = {
            [18157] = { helpText = "Inside Temple of Earth (Deepholm instance).", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Deepholm, x = 49.7, y = 54.9, title = "Elder Stonebrand (Temple of Earth)" } } } } },
            [18159] = { helpText = "Uldum.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Uldum, x = 65.5, y = 18.7, title = "Elder Menkhaf" } } } } },
            [18160] = { helpText = "Uldum.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Uldum, x = 31.6, y = 63, title = "Elder Sekhemi" } } } } },
            [18161] = { helpText = "Twilight Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_TwilightHighlands, x = 50.9, y = 70.4, title = "Elder Firebeard" } } } } },
            [18162] = { helpText = "Twilight Highlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_TwilightHighlands, x = 51.8, y = 33.1, title = "Elder Darkfeather" } } } } },
            [18156] = { helpText = "Mount Hyjal.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_MountHyjal, x = 26.7, y = 62, title = "Elder Windsong" } } } } },
            [18155] = { helpText = "Nordrassil, Mount Hyjal.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_MountHyjal, x = 62.6, y = 22.8, title = "Elder Evershade" } } } } },
            [18154] = { helpText = "Vashj'ir.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Vashjir, x = 69, y = 82, title = "Elder Moonlance" } } } } },
            [18158] = { helpText = "Deepholm.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_Deepholm, x = 27.7, y = 69.2, title = "Elder Deepforge" } } } } },
        },
    },
    [912] = {
        helpText = "Visit all 17 Eastern Kingdoms elders during Lunar Festival. Includes open-world and dungeon elders (Scholomance, Zul'Gurub).",
        criteria = {
            [1922] = { helpText = "Kharanos, Dun Morogh.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DunMorogh, x = 53.9, y = 49.9, title = "Elder Goldwell" } } } } },
            [1923] = { helpText = "Blasted Lands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BlastedLands, x = 54.3, y = 49.5, title = "Elder Bellowrage" } } } } },
            [1924] = { helpText = "Goldshire, Elwynn Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ElwynnForest, x = 39.8, y = 63.7, title = "Elder Stormbrow" } } } } },
            [1925] = { helpText = "Western Plaguelands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_WesternPlaguelands, x = 63.5, y = 36.1, title = "Elder Meadowrun" } } } } },
            [1926] = { helpText = "Zul'Gurub (instance).", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernStranglethorn, x = 71, y = 34.3, title = "Elder Starglade (Zul'Gurub area)" } } } } },
            [1927] = { helpText = "Booty Bay, Cape of Stranglethorn.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheCapeOfStranglethorn, x = 39.9, y = 72.5, title = "Elder Winterhoof" } } } } },
            [1937] = { helpText = "Thelsamar, Loch Modan.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_LochModan, x = 33, y = 46, title = "Elder Silvervein" } } } } },
            [1938] = { helpText = "Sentinel Hill, Westfall.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Westfall, x = 56.6, y = 47, title = "Elder Skychaser" } } } } },
            [1939] = { helpText = "Burning Steppes.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BurningSteppes, x = 70.1, y = 45.4, title = "Elder Rumblerock" } } } } },
            [1940] = { helpText = "Flame Crest, Burning Steppes.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BurningSteppes, x = 53.6, y = 24.5, title = "Elder Dawnstrider" } } } } },
            [1941] = { helpText = "The Hinterlands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheHinterlands, x = 49, y = 47.9, title = "Elder Highpeak" } } } } },
            [1942] = { helpText = "Searing Gorge.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SearingGorge, x = 21.3, y = 79.1, title = "Elder Ironband" } } } } },
            [1944] = { helpText = "Brill, Tirisfal Glades.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TirisfalGlades, x = 61.8, y = 53.9, title = "Elder Graveborn" } } } } },
            [1945] = { helpText = "The Sepulcher, Silverpine Forest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SilverpineForest, x = 45, y = 41.1, title = "Elder Obsidian" } } } } },
            [1946] = { helpText = "Eastern Plaguelands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_EasternPlaguelands, x = 35.6, y = 68.8, title = "Elder Windrun" } } } } },
            [1947] = { helpText = "Light's Hope Chapel, Eastern Plaguelands.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_EasternPlaguelands, x = 75.7, y = 54.5, title = "Elder Snowcrown" } } } } },
            [1950] = { helpText = "Scholomance (instance).", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_WesternPlaguelands, x = 69.2, y = 73.5, title = "Elder Moonstrike (Scholomance)" } } } } },
        },
    },
    [911] = {
        helpText = "Visit all 21 Kalimdor elders during Lunar Festival. Includes open-world and dungeon elders (Dire Maul, Maraudon, Zul'Farrak).",
        criteria = {
            [1916] = { helpText = "Razor Hill, Durotar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Durotar, x = 53.2, y = 43.6, title = "Elder Runetotem" } } } } },
            [1917] = { helpText = "Azshara.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Azshara, x = 64.7, y = 79.3, title = "Elder Skygleam" } } } } },
            [1918] = { helpText = "The Crossroads, Northern Barrens.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernBarrens, x = 48.5, y = 59.3, title = "Elder Moonwarden" } } } } },
            [1919] = { helpText = "Vendetta Point, Southern Barrens.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 41.5, y = 47.5, title = "Elder High Mountain" } } } } },
            [1920] = { helpText = "Ratchet, Northern Barrens.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernBarrens, x = 68.4, y = 70, title = "Elder Windtotem" } } } } },
            [1951] = { helpText = "Dolanaar, Teldrassil.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Teldrassil, x = 57, y = 53, title = "Elder Bladeleaf" } } } } },
            [1952] = { helpText = "Lor'danel, Darkshore.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Darkshore, x = 49.5, y = 19, title = "Elder Starweave" } } } } },
            [1953] = { helpText = "Bloodhoof Village, Mulgore.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Mulgore, x = 48.3, y = 53.4, title = "Elder Bloodhoof" } } } } },
            [1954] = { helpText = "Astranaar, Ashenvale.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 35.6, y = 48.9, title = "Elder Riversong" } } } } },
            [1955] = { helpText = "Feralas.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 76.7, y = 37.9, title = "Elder Grimtotem" } } } } },
            [1956] = { helpText = "Dire Maul (instance).", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 62.6, y = 31.1, title = "Elder Mistwalker (Dire Maul)" } } } } },
            [1957] = { helpText = "Felwood.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Felwood, x = 38.3, y = 52.9, title = "Elder Nightwind" } } } } },
            [1958] = { helpText = "Freewind Post, Thousand Needles.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ThousandNeedles, x = 46.4, y = 51, title = "Elder Skyseer" } } } } },
            [1959] = { helpText = "Fizzle and Pozzik's Speedbarge, Thousand Needles.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ThousandNeedles, x = 77.1, y = 75.6, title = "Elder Morningdew" } } } } },
            [1960] = { helpText = "Tanaris.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 37.2, y = 79.1, title = "Elder Ragetotem" } } } } },
            [1961] = { helpText = "Gadgetzan, Tanaris.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 51.3, y = 28.8, title = "Elder Dreamseer" } } } } },
            [1962] = { helpText = "Un'Goro Crater.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_UnGoroCrater, x = 50.4, y = 76.1, title = "Elder Thunderhorn" } } } } },
            [1963] = { helpText = "Winterspring.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Winterspring, x = 53.2, y = 56.8, title = "Elder Brightspear" } } } } },
            [1964] = { helpText = "Everlook, Winterspring.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Winterspring, x = 60.1, y = 49.9, title = "Elder Stonespire" } } } } },
            [1965] = { helpText = "Silithus.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Silithus, x = 30.8, y = 13.3, title = "Elder Primestone" } } } } },
            [1966] = { helpText = "Cenarion Hold, Silithus.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Silithus, x = 53, y = 35.5, title = "Elder Bladesing" } } } } },
        },
    },
    [910] = {
        helpText = "Visit all 13 dungeon elders during Lunar Festival. Dungeons: Zul'Farrak, Sunken Temple, Maraudon, Blackrock Spire, Blackrock Depths, Stratholme, Utgarde Keep, The Nexus, Azjol-Nerub, Drak'Tharon Keep, Gundrak, Halls of Stone, Utgarde Pinnacle.",
        criteria = {
            [1910] = { helpText = "Zul'Farrak.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 42.4, y = 43.4, title = "Elder Wildmane (Zul'Farrak)" } } } } },
            [1911] = { helpText = "Sunken Temple.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernStranglethorn, x = 62.9, y = 34.5, title = "Elder Starsong (Sunken Temple)" } } } } },
            [1912] = { helpText = "Maraudon.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Desolace, x = 51.5, y = 93.7, title = "Elder Splitrock (Maraudon)" } } } } },
            [1913] = { helpText = "Blackrock Spire.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BurningSteppes, x = 61.9, y = 39.9, title = "Elder Stonefort (Blackrock Spire)" } } } } },
            [1914] = { helpText = "Blackrock Depths.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SearingGorge, x = 50.5, y = 63, title = "Elder Morndeep (Blackrock Depths)" } } } } },
            [1915] = { helpText = "Stratholme.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_EasternPlaguelands, x = 78.6, y = 21.9, title = "Elder Farwhisper (Stratholme)" } } } } },
            [5259] = { helpText = "Utgarde Keep.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_HowlingFjord, x = 47.6, y = 70.2, title = "Elder Jarten (Utgarde Keep)" } } } } },
            [5260] = { helpText = "The Nexus.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_BoreanTundra, x = 55.21, y = 64.73, title = "Elder Igasho (The Nexus)" } } } } },
            [5261] = { helpText = "Azjol-Nerub.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_Dragonblight, x = 21.8, y = 43.6, title = "Elder Nurgen (Azjol-Nerub)" } } } } },
            [5262] = { helpText = "Drak'Tharon Keep.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_ZulDrak, x = 68.6, y = 80.9, title = "Elder Kilias (Drak'Tharon Keep)" } } } } },
            [5263] = { helpText = "Gundrak.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_ZulDrak, x = 45.6, y = 62, title = "Elder Ohanzee (Gundrak)" } } } } },
            [5264] = { helpText = "Halls of Stone.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_TheStormPeaks, x = 29.1, y = 60.9, title = "Elder Yurauk (Halls of Stone)" } } } } },
            [5265] = { helpText = "Utgarde Pinnacle.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_HowlingFjord, x = 48.6, y = 22, title = "Elder Chogan'gada (Utgarde Pinnacle)" } } } } },
        },
    },
    [914] = {
        helpText = "Visit the 3 Horde capital elders: Orgrimmar, Thunder Bluff, Undercity.",
        criteria = {
            [1991] = { helpText = "Orgrimmar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Orgrimmar, x = 52.4, y = 60, title = "Elder Darkhorn" } } } } },
            [1992] = { helpText = "Thunder Bluff.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ThunderBluff, x = 73, y = 23.3, title = "Elder Wheathoof" } } } } },
            [1993] = { helpText = "Undercity.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Undercity, x = 67, y = 38, title = "Elder Darkcore" } } } } },
        },
    },
    [915] = {
        helpText = "Visit the 3 Alliance capital elders: Darnassus, Ironforge, Stormwind.",
        criteria = {
            [1999] = { helpText = "Darnassus.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Darnassus, x = 33, y = 14, title = "Elder Bladeswift" } } } } },
            [1997] = { helpText = "Ironforge.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ironforge, x = 29, y = 16, title = "Elder Bronzebeard" } } } } },
            [1998] = { helpText = "Stormwind.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StormwindCity, x = 21, y = 54, title = "Elder Hammershout" } } } } },
        },
    },
    [1396] = {
        helpText = "Visit all 18 Northrend elders during Lunar Festival. Open-world and dungeon elders (The Nexus, Azjol-Nerub, Utgarde Keep/Pinnacle, Drak'Tharon Keep, Gundrak, Halls of Stone).",
        criteria = {
            [5141] = { helpText = "Valiance Keep, Borean Tundra.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_BoreanTundra, x = 59.1, y = 65.6, title = "Elder Sardis" } } } } },
            [5142] = { helpText = "Westfall Brigade, Grizzly Hills.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_GrizzlyHills, x = 60.5, y = 27.6, title = "Elder Beldak" } } } } },
            [5143] = { helpText = "Star's Rest, Dragonblight.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_Dragonblight, x = 29.9, y = 56.1, title = "Elder Morthie" } } } } },
            [5144] = { helpText = "Frosthold, The Storm Peaks.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_TheStormPeaks, x = 28.9, y = 73.7, title = "Elder Fargal" } } } } },
            [5145] = { helpText = "D.E.H.T.A, Borean Tundra.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_BoreanTundra, x = 57, y = 43, title = "Elder Arp" } } } } },
            [5146] = { helpText = "Transitus Shield, Borean Tundra.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_BoreanTundra, x = 33, y = 34, title = "Elder Northal" } } } } },
            [5147] = { helpText = "Lakeside Landing, Sholazar Basin.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_SholazarBasin, x = 49, y = 63, title = "Elder Sandrene" } } } } },
            [5148] = { helpText = "Rainspeaker Rapids, Sholazar Basin.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_SholazarBasin, x = 63, y = 49, title = "Elder Wanikaya" } } } } },
            [5149] = { helpText = "Ruins of Tethys, Grizzly Hills.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_GrizzlyHills, x = 80, y = 37.1, title = "Elder Lunaro" } } } } },
            [5150] = { helpText = "Wintergrasp.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_Wintergrasp, x = 49, y = 13.9, title = "Elder Bluewolf" } } } } },
            [5151] = { helpText = "Zim'Torga, Zul'Drak.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_ZulDrak, x = 58, y = 56, title = "Elder Tauros" } } } } },
            [5154] = { helpText = "Moa'ki Harbor, Dragonblight.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_Dragonblight, x = 48, y = 78, title = "Elder Thoim" } } } } },
            [5155] = { helpText = "K3, The Storm Peaks.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_TheStormPeaks, x = 41, y = 84, title = "Elder Graymane" } } } } },
            [5156] = { helpText = "Bouldercrag's Refuge, The Storm Peaks.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_TheStormPeaks, x = 30, y = 38, title = "Elder Stonebeard" } } } } },
            [5157] = { helpText = "Warsong Hold, Borean Tundra.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_BoreanTundra, x = 42.2, y = 49.5, title = "Elder Pamuya" } } } } },
            [5158] = { helpText = "Camp Oneqwah, Grizzly Hills.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_GrizzlyHills, x = 64.1, y = 47, title = "Elder Whurain" } } } } },
            [5159] = { helpText = "Agmar's Hammer, Dragonblight.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_Dragonblight, x = 35, y = 48, title = "Elder Skywarden" } } } } },
            [5160] = { helpText = "Camp Tunka'lo, The Storm Peaks.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOTLK_ZONE_TheStormPeaks, x = 64, y = 51, title = "Elder Muraco" } } } } },
        },
    },
    [609] = {
        helpText = "Receive 50 Coins of Ancestry during Lunar Festival. Earn coins by visiting elders (one per elder per year) and completing the Lunar Preservation quest (25 coins, once per character).",
        criteria = {
            [472] = { helpText = "Visit elders and complete Lunar Preservation for coins.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Moonglade, x = 53.2, y = 36, title = "Lunar Preservation (Myrael Lunarbloom)" } } } } },
        },
    },
    [626] = {
        helpText = "Purchase and wear Lunar Festival Finery (festival outfit) from a Lunar Festival vendor in Moonglade or capital cities.",
    },
    [1281] = {
        helpText = "Shoot off 10 Red Rocket Clusters in 25 seconds or less during Lunar Festival. Buy Red Rocket Clusters from festival vendors.",
        criteria = {
            [3932] = { helpText = "Use 10 Red Rocket Clusters within 25 seconds.", waypoints = {} },
        },
    },
    [1552] = {
        helpText = "Shoot off 10 Festival Firecrackers in 30 seconds or less during Lunar Festival. Buy Festival Firecrackers from festival vendors.",
        criteria = {
            [5755] = { helpText = "Use 10 Festival Firecrackers within 30 seconds.", waypoints = {} },
        },
    },
    [937] = {
        helpText = "Receive Elune's Blessing by completing the quest during Lunar Festival in Moonglade.",
    },
}
