-- Waypoints for "Hallowed Be Thy Name" (1656) - Hallow's End (event 324)
-- Part of What a Long, Strange Trip It's Been (2144)
-- Criteria for "Tricks and Treats of Azeroth" (971) sub-achievements
-- Horde: 967 (Eastern Kingdoms), 965 (Kalimdor), 968 (Outland)
-- Alliance: 966 (Eastern Kingdoms), 963 (Kalimdor), 969 (Outland)

WhatALongStrangeTripItsBeen_HallowedBeThyNameWaypoints = {
    [971] = {
        helpText = "Tricks and Treats of Azeroth: Complete Tricks and Treats of Eastern Kingdoms, Kalimdor, and Outland (Horde 967/965/968 or Alliance 966/963/969). Use the candy bucket in each inn to get treats.",
    },
    [967] = {
        helpText = "Tricks and Treats of Eastern Kingdoms: Use the candy bucket in each inn across Eastern Kingdoms during Hallow's End.",
        criteria = {
            [2147] = { helpText = "Arathi Highlands, Hammerfall.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ArathiHighlands, x = 69, y = 33.2, title = "Arathi Highlands, Hammerfall" } } } } },
            [18429] = { helpText = "Badlands, Fuselight.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Badlands, x = 65.9, y = 35.8, title = "Badlands, Fuselight" } } } } },
            [17626] = { helpText = "Badlands, New Kargath.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Badlands, x = 18.3, y = 42.8, title = "Badlands, New Kargath" } } } } },
            [17627] = { helpText = "Blasted Lands, Dreadmaul Hold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BlastedLands, x = 40.5, y = 11.4, title = "Blasted Lands, Dreadmaul Hold" } } } } },
            [2144] = { helpText = "The Cape of Stranglethorn, Booty Bay.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheCapeOfStranglethorn, x = 40.9, y = 73.8, title = "The Cape of Stranglethorn, Booty Bay" } } } } },
            [17633] = { helpText = "The Cape of Stranglethorn, Hardwrench Hideaway.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheCapeOfStranglethorn, x = 35.1, y = 27.3, title = "The Cape of Stranglethorn, Hardwrench Hideaway" } } } } },
            [2143] = { helpText = "Eastern Plaguelands, Light's Hope Chapel.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_EasternPlaguelands, x = 75.6, y = 52.4, title = "Eastern Plaguelands, Light's Hope Chapel" } } } } },
            [2149] = { helpText = "Eversong Woods, Fairbreeze Village.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_EversongWoods, x = 43.7, y = 71.1, title = "Eversong Woods, Fairbreeze Village" } } } } },
            [2150] = { helpText = "Eversong Woods, Falconwing Square.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_EversongWoods, x = 48.1, y = 47.8, title = "Eversong Woods, Falconwing Square" } } } } },
            [2151] = { helpText = "Ghostlands, Tranquillien.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ghostlands, x = 48.6, y = 32, title = "Ghostlands, Tranquillien" } } } } },
            [17628] = { helpText = "Hillsbrad Foothills, Eastpoint Tower.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_HillsbradFoothills, x = 60.3, y = 63.8, title = "Hillsbrad Foothills, Eastpoint Tower" } } } } },
            [2152] = { helpText = "Hillsbrad Foothills, Tarren Mill.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_HillsbradFoothills, x = 57.9, y = 47.3, title = "Hillsbrad Foothills, Tarren Mill" } } } } },
            [17629] = { helpText = "The Hinterlands, Hiri'watha Research Station.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheHinterlands, x = 31.9, y = 57.9, title = "The Hinterlands, Hiri'watha Research Station" } } } } },
            [2153] = { helpText = "The Hinterlands, Revantusk Village.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheHinterlands, x = 78.2, y = 81.4, title = "The Hinterlands, Revantusk Village" } } } } },
            [2157] = { helpText = "Northern Stranglethorn, Grom'gol Base Camp.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernStranglethorn, x = 37.3, y = 51.8, title = "Northern Stranglethorn, Grom'gol Base Camp" } } } } },
            [18430] = { helpText = "Searing Gorge, Iron Summit.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SearingGorge, x = 39.5, y = 66.2, title = "Searing Gorge, Iron Summit" } } } } },
            [2154] = { helpText = "Silvermoon City, The Bazaar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_SilvermoonCity, x = 67.6, y = 73.3, title = "Silvermoon City, The Bazaar" } } } } },
            [2155] = { helpText = "Silvermoon City, The Royal Exchange.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_SilvermoonCity, x = 79.7, y = 58, title = "Silvermoon City, The Royal Exchange" } } } } },
            [17631] = { helpText = "Silverpine Forest, Forsaken Rear Guard.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SilverpineForest, x = 44.3, y = 20.4, title = "Silverpine Forest, Forsaken Rear Guard" } } } } },
            [2156] = { helpText = "Silverpine Forest, The Sepulcher.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SilverpineForest, x = 46.4, y = 42.8, title = "Silverpine Forest, The Sepulcher" } } } } },
            [18431] = { helpText = "Swamp of Sorrows, Bogpaddle.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SwampOfSorrows, x = 71.7, y = 14.1, title = "Swamp of Sorrows, Bogpaddle" } } } } },
            [2158] = { helpText = "Swamp of Sorrows, Stonard.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SwampOfSorrows, x = 46.9, y = 56.7, title = "Swamp of Sorrows, Stonard" } } } } },
            [2159] = { helpText = "Tirisfal Glades, Brill.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TirisfalGlades, x = 61, y = 51.5, title = "Tirisfal Glades, Brill" } } } } },
            [17634] = { helpText = "Tirisfal Glades, The Bulwark.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TirisfalGlades, x = 83, y = 72, title = "Tirisfal Glades, The Bulwark" } } } } },
            [2160] = { helpText = "Undercity, The Trade Quarter.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Undercity, x = 67.8, y = 37.9, title = "Undercity, The Trade Quarter" } } } } },
            [17635] = { helpText = "Western Plaguelands, Andorhal.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_WesternPlaguelands, x = 48.2, y = 63.8, title = "Western Plaguelands, Andorhal" } } } } },
        },
    },
    [965] = {
        helpText = "Tricks and Treats of Kalimdor: Use the candy bucket in each inn across Kalimdor during Hallow's End.",
        criteria = {
            [17610] = { helpText = "Ashenvale, Hellscream's Watch.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 38.6, y = 42.4, title = "Ashenvale, Hellscream's Watch" } } } } },
            [17611] = { helpText = "Ashenvale, Silverwind Refuge.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 50.2, y = 67.2, title = "Ashenvale, Silverwind Refuge" } } } } },
            [2105] = { helpText = "Ashenvale, Splintertree Post.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 73.9, y = 60.6, title = "Ashenvale, Splintertree Post" } } } } },
            [17612] = { helpText = "Ashenvale, Zoram'gar Outpost.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 12.9, y = 34.1, title = "Ashenvale, Zoram'gar Outpost" } } } } },
            [17613] = { helpText = "Azshara, Bilgewater Harbor.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Azshara, x = 57.1, y = 50.2, title = "Azshara, Bilgewater Harbor" } } } } },
            [18396] = { helpText = "Desolace, Karnum's Glade.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Desolace, x = 56.8, y = 50, title = "Desolace, Karnum's Glade" } } } } },
            [2108] = { helpText = "Desolace, Shadowprey Village.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Desolace, x = 24.1, y = 68.3, title = "Desolace, Shadowprey Village" } } } } },
            [2109] = { helpText = "Durotar, Razor Hill.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Durotar, x = 51.6, y = 41.7, title = "Durotar, Razor Hill" } } } } },
            [2110] = { helpText = "Dustwallow Marsh, Brackenwall Village.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DustwallowMarsh, x = 36.8, y = 32.4, title = "Dustwallow Marsh, Brackenwall Village" } } } } },
            [2084] = { helpText = "Dustwallow Marsh, Mudsprocket.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DustwallowMarsh, x = 41.9, y = 74.1, title = "Dustwallow Marsh, Mudsprocket" } } } } },
            [18397] = { helpText = "Felwood, Whisperwind Grove.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Felwood, x = 44.6, y = 29, title = "Felwood, Whisperwind Grove" } } } } },
            [17616] = { helpText = "Feralas, Camp Ataya.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 41.4, y = 15.6, title = "Feralas, Camp Ataya" } } } } },
            [2111] = { helpText = "Feralas, Camp Mojache.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 74.8, y = 45.1, title = "Feralas, Camp Mojache" } } } } },
            [17617] = { helpText = "Feralas, Stonemaul Hold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 52, y = 47.7, title = "Feralas, Stonemaul Hold" } } } } },
            [2112] = { helpText = "Mulgore, Bloodhoof Village.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Mulgore, x = 46.8, y = 60.4, title = "Mulgore, Bloodhoof Village" } } } } },
            [2107] = { helpText = "Northern Barrens, The Crossroads.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernBarrens, x = 49.6, y = 57.9, title = "Northern Barrens, The Crossroads" } } } } },
            [17618] = { helpText = "Northern Barrens, Grol'dom Farm.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernBarrens, x = 56.2, y = 40, title = "Northern Barrens, Grol'dom Farm" } } } } },
            [17619] = { helpText = "Northern Barrens, Nozzlepot's Outpost.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernBarrens, x = 62.5, y = 16.6, title = "Northern Barrens, Nozzlepot's Outpost" } } } } },
            [2083] = { helpText = "Northern Barrens, Ratchet.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernBarrens, x = 67.3, y = 74.6, title = "Northern Barrens, Ratchet" } } } } },
            [2113] = { helpText = "Orgrimmar, Valley of Strength.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Orgrimmar, x = 53.8, y = 78.8, title = "Orgrimmar, Valley of Strength" } } } } },
            [2085] = { helpText = "Silithus, Cenarion Hold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Silithus, x = 55.5, y = 36.8, title = "Silithus, Cenarion Hold" } } } } },
            [17620] = { helpText = "Southern Barrens, Desolation Hold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 40.7, y = 69.4, title = "Southern Barrens, Desolation Hold" } } } } },
            [17621] = { helpText = "Southern Barrens, Hunter's Hill.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 39.3, y = 20.1, title = "Southern Barrens, Hunter's Hill" } } } } },
            [17622] = { helpText = "Stonetalon Mountains, Krom'gar Fortress.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 66.5, y = 64.2, title = "Stonetalon Mountains, Krom'gar Fortress" } } } } },
            [2114] = { helpText = "Stonetalon Mountains, Sun Rock Retreat.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 50.4, y = 63.8, title = "Stonetalon Mountains, Sun Rock Retreat" } } } } },
            [18415] = { helpText = "Tanaris, Bootlegger Outpost.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 55.7, y = 60.9, title = "Tanaris, Bootlegger Outpost" } } } } },
            [2086] = { helpText = "Tanaris, Gadgetzan.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 52.6, y = 27.1, title = "Tanaris, Gadgetzan" } } } } },
            [2115] = { helpText = "Thunder Bluff, Lower Rise.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ThunderBluff, x = 45.7, y = 64.3, title = "Thunder Bluff, Lower Rise" } } } } },
            [18417] = { helpText = "Un'Goro Crater, Marshal's Stand.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_UnGoroCrater, x = 55.2, y = 62.2, title = "Un'Goro Crater, Marshal's Stand" } } } } },
            [2087] = { helpText = "Winterspring, Everlook.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Winterspring, x = 59.8, y = 51.2, title = "Winterspring, Everlook" } } } } },
        },
    },
    [968] = {
        helpText = "Tricks and Treats of Outland: Use the candy bucket in each inn across Outland during Hallow's End.",
        criteria = {
            [2204] = { helpText = "Blade's Edge Mountains, Evergrove.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 63, y = 38, title = "Blade's Edge Mountains, Evergrove" } } } } },
            [2217] = { helpText = "Blade's Edge Mountains, Mok'Nathal Village.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 76, y = 60, title = "Blade's Edge Mountains, Mok'Nathal Village" } } } } },
            [2218] = { helpText = "Blade's Edge Mountains, Thunderlord Stronghold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 53, y = 55, title = "Blade's Edge Mountains, Thunderlord Stronghold" } } } } },
            [2219] = { helpText = "Hellfire Peninsula, Falcon Watch.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_HellfirePeninsula, x = 27, y = 60, title = "Hellfire Peninsula, Falcon Watch" } } } } },
            [2221] = { helpText = "Hellfire Peninsula, Thrallmar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_HellfirePeninsula, x = 57, y = 38, title = "Hellfire Peninsula, Thrallmar" } } } } },
            [2220] = { helpText = "Nagrand, Garadar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Nagrand, x = 57, y = 35, title = "Nagrand, Garadar" } } } } },
            [2205] = { helpText = "Netherstorm, Area 52.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Netherstorm, x = 32, y = 64, title = "Netherstorm, Area 52" } } } } },
            [2206] = { helpText = "Netherstorm, The Stormspire.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Netherstorm, x = 43, y = 36, title = "Netherstorm, The Stormspire" } } } } },
            [2210] = { helpText = "Shadowmoon Valley, Altar of Sha'tar or Sanctum of the Stars.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_ShadowmoonValley, x = 61, y = 28, title = "Shadowmoon Valley, Altar of Sha'tar or Sanctum of the Stars" } } } } },
            [2222] = { helpText = "Shadowmoon Valley, Shadowmoon Village.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_ShadowmoonValley, x = 29.2, y = 28.1, title = "Shadowmoon Valley, Shadowmoon Village" } } } } },
            [2207] = { helpText = "Shattrath City, Aldor Rise or Scryer's Tier.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_ShattrathCity, x = 56.2, y = 81.7, title = "Shattrath City, Aldor Rise or Scryer's Tier" } } } } },
            [2223] = { helpText = "Terokkar Forest, Stonebreaker Hold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_TerokkarForest, x = 49, y = 45, title = "Terokkar Forest, Stonebreaker Hold" } } } } },
            [2224] = { helpText = "Zangarmarsh, Zabra'jin.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Zangarmarsh, x = 30, y = 51, title = "Zangarmarsh, Zabra'jin" } } } } },
            [2209] = { helpText = "Zangarmarsh, Cenarion Refuge.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Zangarmarsh, x = 79, y = 63, title = "Zangarmarsh, Cenarion Refuge" } } } } },
        },
    },
    -- Alliance achievements
    [966] = {
        helpText = "Tricks and Treats of Eastern Kingdoms (Alliance): Use the candy bucket in each inn across Eastern Kingdoms during Hallow's End.",
        criteria = {
            [28954] = { helpText = "Arathi Highlands, Refuge Pointe.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ArathiHighlands, x = 40.09, y = 49.14, title = "Arathi Highlands, Refuge Pointe" } } } } },
            [28955] = { helpText = "Badlands, Fuselight.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Badlands, x = 65.86, y = 35.65, title = "Badlands, Fuselight" } } } } },
            [28956] = { helpText = "Badlands, Dragon's Mouth.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Badlands, x = 20.87, y = 56.32, title = "Badlands, Dragon's Mouth" } } } } },
            [28960] = { helpText = "Blasted Lands, Nethergarde Keep.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BlastedLands, x = 60.69, y = 14.07, title = "Blasted Lands, Nethergarde Keep" } } } } },
            [28961] = { helpText = "Blasted Lands, Surwich.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_BlastedLands, x = 44.34, y = 87.59, title = "Blasted Lands, Surwich" } } } } },
            [12332] = { helpText = "Dun Morogh, Kharanos.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DunMorogh, x = 54.48, y = 50.76, title = "Dun Morogh, Kharanos" } } } } },
            [12335] = { helpText = "Ironforge, The Commons.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ironforge, x = 18.5, y = 50.83, title = "Ironforge, The Commons" } } } } },
            [12344] = { helpText = "Duskwood, Darkshire.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Duskwood, x = 73.8, y = 44.25, title = "Duskwood, Darkshire" } } } } },
            [12402] = { helpText = "Eastern Plaguelands, Light's Hope Chapel.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_EasternPlaguelands, x = 75.57, y = 52.3, title = "Eastern Plaguelands, Light's Hope Chapel" } } } } },
            [12286] = { helpText = "Elwynn Forest, Goldshire.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_ElwynnForest, x = 43.74, y = 65.9, title = "Elwynn Forest, Goldshire" } } } } },
            [12336] = { helpText = "Stormwind, The Trade District.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StormwindCity, x = 60.51, y = 75.32, title = "Stormwind, The Trade District" } } } } },
            [12351] = { helpText = "The Hinterlands, Aerie Peak.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheHinterlands, x = 14.19, y = 44.6, title = "The Hinterlands, Aerie Peak" } } } } },
            [28970] = { helpText = "The Hinterlands, Stormfeather Outpost.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheHinterlands, x = 66.16, y = 44.43, title = "The Hinterlands, Stormfeather Outpost" } } } } },
            [12339] = { helpText = "Loch Modan, Thelsamar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_LochModan, x = 35.54, y = 48.5, title = "Loch Modan, Thelsamar" } } } } },
            [28963] = { helpText = "Loch Modan, Farstrider Lodge.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_LochModan, x = 83.03, y = 63.53, title = "Loch Modan, Farstrider Lodge" } } } } },
            [12342] = { helpText = "Redridge Mountains, Lakeshire.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_RedridgeMountains, x = 26.48, y = 41.56, title = "Redridge Mountains, Lakeshire" } } } } },
            [28965] = { helpText = "Searing Gorge, Iron Summit.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SearingGorge, x = 39.48, y = 66.03, title = "Searing Gorge, Iron Summit" } } } } },
            [28964] = { helpText = "Northern Stranglethorn, Fort Livingston.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernStranglethorn, x = 53.16, y = 66.98, title = "Northern Stranglethorn, Fort Livingston" } } } } },
            [12397] = { helpText = "The Cape of Stranglethorn, Booty Bay.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_TheCapeOfStranglethorn, x = 40.91, y = 73.72, title = "The Cape of Stranglethorn, Booty Bay" } } } } },
            [28967] = { helpText = "Swamp of Sorrows, Bogpaddle.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SwampOfSorrows, x = 71.65, y = 14.1, title = "Swamp of Sorrows, Bogpaddle" } } } } },
            [28968] = { helpText = "Swamp of Sorrows, The Harborage.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_SwampOfSorrows, x = 28.93, y = 32.4, title = "Swamp of Sorrows, The Harborage" } } } } },
            [28988] = { helpText = "Western Plaguelands, Chillwind Camp.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_WesternPlaguelands, x = 43.41, y = 84.39, title = "Western Plaguelands, Chillwind Camp" } } } } },
            [12340] = { helpText = "Westfall, Sentinel Hill.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Westfall, x = 52.91, y = 53.74, title = "Westfall, Sentinel Hill" } } } } },
            [12343] = { helpText = "Wetlands, Menethil Harbor.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Wetlands, x = 10.81, y = 60.95, title = "Wetlands, Menethil Harbor" } } } } },
            [28990] = { helpText = "Wetlands, Swiftgear Station.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Wetlands, x = 26.09, y = 25.97, title = "Wetlands, Swiftgear Station" } } } } },
            [28991] = { helpText = "Wetlands, Greenwarden's Grove.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Wetlands, x = 58.18, y = 39.21, title = "Wetlands, Greenwarden's Grove" } } } } },
        },
    },
    [963] = {
        helpText = "Tricks and Treats of Kalimdor (Alliance): Use the candy bucket in each inn across Kalimdor during Hallow's End.",
        criteria = {
            [12345] = { helpText = "Ashenvale, Astranaar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Ashenvale, x = 37.01, y = 49.26, title = "Ashenvale, Astranaar" } } } } },
            [12333] = { helpText = "Azuremyst Isle, Azure Watch.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_AzuremystIsle, x = 48.49, y = 49.05, title = "Azuremyst Isle, Azure Watch" } } } } },
            [12337] = { helpText = "The Exodar, Seat of the Naaru.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_TheExodar, x = 59.25, y = 18.47, title = "The Exodar, Seat of the Naaru" } } } } },
            [12341] = { helpText = "Bloodmyst Isle, Blood Watch.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BloodmystIsle, x = 55.69, y = 59.97, title = "Bloodmyst Isle, Blood Watch" } } } } },
            [28951] = { helpText = "Darkshore, Lor'danel.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Darkshore, x = 50.8, y = 18.9, title = "Darkshore, Lor'danel" } } } } },
            [12334] = { helpText = "Darnassus, Craftsmen's Terrace.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Darnassus, x = 62.27, y = 33.16, title = "Darnassus, Craftsmen's Terrace" } } } } },
            [12348] = { helpText = "Desolace, Nijel's Point.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Desolace, x = 66.33, y = 6.59, title = "Desolace, Nijel's Point" } } } } },
            [28993] = { helpText = "Desolace, Karnum's Glade.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Desolace, x = 56.72, y = 50.12, title = "Desolace, Karnum's Glade" } } } } },
            [12349] = { helpText = "Dustwallow Marsh, Theramore Isle.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DustwallowMarsh, x = 66.6, y = 45.28, title = "Dustwallow Marsh, Theramore Isle" } } } } },
            [12398] = { helpText = "Dustwallow Marsh, Mudsprocket.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_DustwallowMarsh, x = 41.86, y = 74.09, title = "Dustwallow Marsh, Mudsprocket" } } } } },
            [28994] = { helpText = "Felwood, Whisperwind Grove.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Felwood, x = 44.58, y = 28.98, title = "Felwood, Whisperwind Grove" } } } } },
            [28995] = { helpText = "Felwood, Talonbranch Glade.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Felwood, x = 61.86, y = 26.71, title = "Felwood, Talonbranch Glade" } } } } },
            [12350] = { helpText = "Feralas, Feathermoon Stronghold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 46.33, y = 45.19, title = "Feralas, Feathermoon Stronghold" } } } } },
            [28952] = { helpText = "Feralas, Dreamer's Rest.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Feralas, x = 51.07, y = 17.82, title = "Feralas, Dreamer's Rest" } } } } },
            [12396] = { helpText = "Northern Barrens, Ratchet.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_NorthernBarrens, x = 67.34, y = 74.66, title = "Northern Barrens, Ratchet" } } } } },
            [29006] = { helpText = "Southern Barrens, Honor's Stand.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 39.01, y = 10.98, title = "Southern Barrens, Honor's Stand" } } } } },
            [29007] = { helpText = "Southern Barrens, Northwatch Hold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 65.6, y = 46.54, title = "Southern Barrens, Northwatch Hold" } } } } },
            [29008] = { helpText = "Southern Barrens, Fort Triumph.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.CATA_ZONE_SouthernBarrens, x = 49.06, y = 68.5, title = "Southern Barrens, Fort Triumph" } } } } },
            [12347] = { helpText = "Stonetalon Mountains, Stonetalon Peak.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 40.53, y = 17.69, title = "Stonetalon Mountains, Stonetalon Peak" } } } } },
            [29010] = { helpText = "Stonetalon Mountains, Northwatch Expedition Base.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 71.02, y = 79.08, title = "Stonetalon Mountains, Northwatch Expedition Base" } } } } },
            [29011] = { helpText = "Stonetalon Mountains, Windshear Hold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 59.05, y = 56.33, title = "Stonetalon Mountains, Windshear Hold" } } } } },
            [29012] = { helpText = "Stonetalon Mountains, Thal'darah Overlook.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 39.48, y = 32.81, title = "Stonetalon Mountains, Thal'darah Overlook" } } } } },
            [29013] = { helpText = "Stonetalon Mountains, Farwatcher's Glen.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_StonetalonMountains, x = 31.53, y = 60.66, title = "Stonetalon Mountains, Farwatcher's Glen" } } } } },
            [12399] = { helpText = "Tanaris, Gadgetzan.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 52.56, y = 27.1, title = "Tanaris, Gadgetzan" } } } } },
            [29014] = { helpText = "Tanaris, Bootlegger Outpost.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Tanaris, x = 55.7, y = 60.96, title = "Tanaris, Bootlegger Outpost" } } } } },
            [12331] = { helpText = "Teldrassil, Dolanaar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Teldrassil, x = 55.36, y = 52.29, title = "Teldrassil, Dolanaar" } } } } },
            [12401] = { helpText = "Silithus, Cenarion Hold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Silithus, x = 55.47, y = 36.79, title = "Silithus, Cenarion Hold" } } } } },
            [29018] = { helpText = "Un'Goro Crater, Marshal's Stand.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_UnGoroCrater, x = 55.27, y = 62.12, title = "Un'Goro Crater, Marshal's Stand" } } } } },
            [12400] = { helpText = "Winterspring, Everlook.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.WOW_ZONE_Winterspring, x = 59.83, y = 51.22, title = "Winterspring, Everlook" } } } } },
        },
    },
    [969] = {
        helpText = "Tricks and Treats of Outland (Alliance): Use the candy bucket in each inn across Outland during Hallow's End.",
        criteria = {
            [12406] = { helpText = "Blade's Edge Mountains, Evergrove.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 62.9, y = 38.3, title = "Blade's Edge Mountains, Evergrove" } } } } },
            [12358] = { helpText = "Blade's Edge Mountains, Sylvanaar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 35.8, y = 63.8, title = "Blade's Edge Mountains, Sylvanaar" } } } } },
            [12359] = { helpText = "Blade's Edge Mountains, Toshley's Station.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_BladesEdgeMountains, x = 61, y = 68.1, title = "Blade's Edge Mountains, Toshley's Station" } } } } },
            [12352] = { helpText = "Hellfire Peninsula, Honor Hold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_HellfirePeninsula, x = 54.3, y = 63.6, title = "Hellfire Peninsula, Honor Hold" } } } } },
            [12353] = { helpText = "Hellfire Peninsula, Temple of Telhamat.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_HellfirePeninsula, x = 23.4, y = 36.5, title = "Hellfire Peninsula, Temple of Telhamat" } } } } },
            [12357] = { helpText = "Nagrand, Telaar.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Nagrand, x = 54.2, y = 75.8, title = "Nagrand, Telaar" } } } } },
            [12407] = { helpText = "Netherstorm, Area 52.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Netherstorm, x = 32, y = 64.4, title = "Netherstorm, Area 52" } } } } },
            [12408] = { helpText = "Netherstorm, The Stormspire.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Netherstorm, x = 43.4, y = 36.1, title = "Netherstorm, The Stormspire" } } } } },
            [12360] = { helpText = "Shadowmoon Valley, Wildhammer Stronghold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_ShadowmoonValley, x = 37.1, y = 58.2, title = "Shadowmoon Valley, Wildhammer Stronghold" } } } } },
            [12404] = { helpText = "Shattrath City, Aldor Rise or Scryer's Tier.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_ShattrathCity, x = 56.2, y = 81.7, title = "Shattrath City, Aldor Rise or Scryer's Tier" } } } } },
            [12356] = { helpText = "Terokkar Forest, Allerian Stronghold.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_TerokkarForest, x = 56.6, y = 53.2, title = "Terokkar Forest, Allerian Stronghold" } } } } },
            [12354] = { helpText = "Zangarmarsh, Telredor.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Zangarmarsh, x = 67.2, y = 49, title = "Zangarmarsh, Telredor" } } } } },
            [12355] = { helpText = "Zangarmarsh, Orebor Harborage.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Zangarmarsh, x = 41.9, y = 26.2, title = "Zangarmarsh, Orebor Harborage" } } } } },
            [12403] = { helpText = "Zangarmarsh, Cenarion Refuge.", waypoints = { { kind = "point", coordinates = { { mapId = MapZones.TBC_ZONE_Zangarmarsh, x = 78.5, y = 62.9, title = "Zangarmarsh, Cenarion Refuge" } } } } },
        },
    },
}
